/// Flutter icons Iconhsgfamily
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconhsgfamily
///      fonts:
///       - asset: fonts/Iconhsgfamily.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsHSG {
  IconsHSG._();

  static const _kFontFam = 'IconsHSG';
  static const _kFontPkg = null;

  static const IconData hsg_it = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attendance = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_new = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mahkota = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person2 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
